// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketPortalLibrary.Models;

#nullable disable

namespace TicketPortalLibrary.Migrations
{
    [DbContext(typeof(TicketPortalDbContext))]
    [Migration("20260120173002_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TicketPortalLibrary.Models.Department", b =>
                {
                    b.Property<string>("DepartmentId")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("TicketPortalLibrary.Models.Employee", b =>
                {
                    b.Property<string>("EmpId")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("DepartmentId")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("EmpId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("TicketPortalLibrary.Models.SLA", b =>
                {
                    b.Property<string>("SlaId")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("ResolutionHours")
                        .HasColumnType("int");

                    b.Property<int>("ResponseTime")
                        .HasColumnType("int");

                    b.HasKey("SlaId");

                    b.ToTable("SLAs");
                });

            modelBuilder.Entity("TicketPortalLibrary.Models.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketId"));

                    b.Property<string>("AssignedToEmpId")
                        .HasColumnType("varchar(5)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByEmpId")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime>("DueAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TicketTypeId")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("TicketId");

                    b.HasIndex("AssignedToEmpId");

                    b.HasIndex("CreatedByEmpId");

                    b.HasIndex("TicketTypeId");

                    b.ToTable("Ticket");
                });

            modelBuilder.Entity("TicketPortalLibrary.Models.TicketReply", b =>
                {
                    b.Property<int>("ReplyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReplyId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("EmployeeEmpId")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("EmployeeEmpId1")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("RepliedByAssignedEmpId")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("RepliedByCreatorEmpId")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.HasKey("ReplyId");

                    b.HasIndex("EmployeeEmpId");

                    b.HasIndex("EmployeeEmpId1");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketReply");
                });

            modelBuilder.Entity("TicketPortalLibrary.Models.TicketType", b =>
                {
                    b.Property<string>("TicketTypeId")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("DepartmentId")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SlaId")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("TicketTypeId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("SlaId");

                    b.ToTable("TicketType");
                });

            modelBuilder.Entity("TicketPortalLibrary.Models.Employee", b =>
                {
                    b.HasOne("TicketPortalLibrary.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("TicketPortalLibrary.Models.Ticket", b =>
                {
                    b.HasOne("TicketPortalLibrary.Models.Employee", "AssignedEmployee")
                        .WithMany("AssignedTickets")
                        .HasForeignKey("AssignedToEmpId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TicketPortalLibrary.Models.Employee", "CreatedByEmployee")
                        .WithMany("CreatedTickets")
                        .HasForeignKey("CreatedByEmpId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TicketPortalLibrary.Models.TicketType", "TicketType")
                        .WithMany("Tickets")
                        .HasForeignKey("TicketTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedEmployee");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("TicketType");
                });

            modelBuilder.Entity("TicketPortalLibrary.Models.TicketReply", b =>
                {
                    b.HasOne("TicketPortalLibrary.Models.Employee", null)
                        .WithMany("ReplyToAssignedTickets")
                        .HasForeignKey("EmployeeEmpId");

                    b.HasOne("TicketPortalLibrary.Models.Employee", null)
                        .WithMany("ReplyToCreatedTickets")
                        .HasForeignKey("EmployeeEmpId1");

                    b.HasOne("TicketPortalLibrary.Models.Ticket", "Ticket")
                        .WithMany("TicketReplies")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("TicketPortalLibrary.Models.TicketType", b =>
                {
                    b.HasOne("TicketPortalLibrary.Models.Department", "Department")
                        .WithMany("TicketTypes")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketPortalLibrary.Models.SLA", "SLA")
                        .WithMany("TicketTypes")
                        .HasForeignKey("SlaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("SLA");
                });

            modelBuilder.Entity("TicketPortalLibrary.Models.Department", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("TicketTypes");
                });

            modelBuilder.Entity("TicketPortalLibrary.Models.Employee", b =>
                {
                    b.Navigation("AssignedTickets");

                    b.Navigation("CreatedTickets");

                    b.Navigation("ReplyToAssignedTickets");

                    b.Navigation("ReplyToCreatedTickets");
                });

            modelBuilder.Entity("TicketPortalLibrary.Models.SLA", b =>
                {
                    b.Navigation("TicketTypes");
                });

            modelBuilder.Entity("TicketPortalLibrary.Models.Ticket", b =>
                {
                    b.Navigation("TicketReplies");
                });

            modelBuilder.Entity("TicketPortalLibrary.Models.TicketType", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
